spring.application.name=sistema-colegio-backend

# 1. Credenciales y ruta de tu base de datos
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Colegio;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Jefferson123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. Configuración de Hibernate / JPA para que te ayude a crear las tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect